image: Visual Studio 2015

environment:
  MSVC_VERSION: "Visual Studio 14"
  INCLUDE: "C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\Include;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\include;C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.10586.0\\ucrt"
  LIB: "C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0\\lib;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\lib;C:\\Program Files (x86)\\Windows Kits\\10\\lib;C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.10586.0\\ucrt\\x86"
  
  matrix:
    -  PYTHON: "C:\\Python35"
       PYTHON_VERSION: 3.5
       PYTHON_ARCH: 32

    -  PYTHON: "C:\\Python36"
       PYTHON_VERSION: 3.6
       PYTHON_ARCH: 32

    -  PYTHON: "C:\\Python37"
       PYTHON_VERSION: 3.7
       PYTHON_ARCH: 32

    -  PYTHON: "C:\\Python35-x64"
       PYTHON_VERSION: 3.5
       PYTHON_ARCH: 64

    -  PYTHON: "C:\\Python36-x64"
       PYTHON_VERSION: 3.6
       PYTHON_ARCH: 64

    -  PYTHON: "C:\\Python37-x64"
       PYTHON_VERSION: 3.7
       PYTHON_ARCH: 64

configuration: Release

init:
  - set PYTHONPATH=%PYTHON%
  - set PYTHONHOME=%PYTHON%
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python -m site
  - python -m pip install -U pip setuptools wheel

for:
  - 
    matrix:
      only:
        - PYTHON_VERSION: 3.5
          PYTHON_ARCH: 32
    install:
        - python setup.py bdist_wheel --python-tag cp35 --plat-name win32

  - 
    matrix:
      only:
        - PYTHON_VERSION: 3.6
          PYTHON_ARCH: 32
    install:
        - python setup.py bdist_wheel --python-tag cp36 --plat-name win32

  - 
    matrix:
      only:
        - PYTHON_VERSION: 3.7
          PYTHON_ARCH: 32
    install:
        - python setup.py bdist_wheel --python-tag cp37 --plat-name win32
        
  - 
    matrix:
      only:
        - PYTHON_VERSION: 3.5
          PYTHON_ARCH: 64
    install:
        - python setup.py bdist_wheel --python-tag cp35 --plat-name win_amd64

  - 
    matrix:
      only:
        - PYTHON_VERSION: 3.6
          PYTHON_ARCH: 64
    install:
        - python setup.py bdist_wheel --python-tag cp36 --plat-name win_amd64

  - 
    matrix:
      only:
        - PYTHON_VERSION: 3.7
          PYTHON_ARCH: 64
    install:
        - python setup.py bdist_wheel --python-tag cp37 --plat-name win_amd64

# Not a project with an msbuild file, build done at install.
build: off

before_test:
  - dir dist
  - for /r %%f in (dist/*) do @set wheelname=%%~nxf
  - echo %wheelname% 
  - for /F "tokens=2 delims='" %%a in ('findstr __version__ py2exe\__init__.py') do @set ver=%%a

test_script:
  - pip install dist/%wheelname%
  - python -c "import py2exe"
  - cd tests
  - python maketest.py
  - cd functional
  - cd tk_test
  - python setup.py py2exe
  - cd dist
  - tk_test.exe
  - cd ..\..
  - cd certifi_test
  - pip install certifi
  - python setup.py py2exe
  - dist\certifi_test.exe
  - rmdir /Q /S dist
  - python setup_zip.py py2exe
  - dist\certifi_test.exe
  - cd ..
  - cd ssl_test
  - python setup.py py2exe
  #- where /r c:\Windows libssl*
  #- where /r c:\Windows libcry*
  - del C:\Windows\System32\libssl*.dll /F
  - del C:\Windows\SysWOW64\libssl*.dll /F
  - del C:\Windows\System32\libcrypto*.dll /F
  - del C:\Windows\SysWOW64\libcrypto*.dll /F
  - dist\ssl_test.exe
  
artifacts:
  - path: 'dist/$(wheelname)'
    name: $(wheelname)

# Deploy build to BinTray
deploy:
  provider: BinTray
  username: alby128
  api_key:
    secure: lAocj5KA9Z9x4BefQBIgNlQJbeW4qPBfCgYVBHMyOP3NgyhnMLmvR57ZCqtCKBlQ
  subject: alby128
  repo: py2exe
  package: py2exe
  version: $(ver)
  publish: true
  override: true
    